#!/usr/bin/env bash
# weekly-metrics.sh — [PROJECT NAME]
# DORA 2025 (METRICS-02): Weekly metrics summary writer
# Run: npm run metrics
# Usage: bash scripts/weekly-metrics.sh [--dry-run] [--days=14]

set -euo pipefail

DAYS=14
DRY_RUN=0

for arg in "$@"; do
  case "$arg" in
    --dry-run)
      DRY_RUN=1
      ;;
    --days=*)
      DAYS="${arg#*=}"
      ;;
    *)
      if [[ "$arg" =~ ^[0-9]+$ ]]; then
        DAYS="$arg"
      else
        echo "Invalid argument: $arg"
        echo "Usage: bash scripts/weekly-metrics.sh [--dry-run] [--days=14]"
        exit 1
      fi
      ;;
  esac
done

if ! [[ "$DAYS" =~ ^[0-9]+$ ]]; then
  echo "Invalid --days value: $DAYS"
  echo "Usage: bash scripts/weekly-metrics.sh [--dry-run] [--days=14]"
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
METRICS_DOC="${REPO_ROOT}/docs/METRICS.md"
SNAPSHOT_UTC="$(date -u +"%Y-%m-%d %H:%M:%SZ")"

if ! git -C "${REPO_ROOT}" rev-parse --git-dir >/dev/null 2>&1; then
  echo "This script must run inside a git repository. Checked path: ${REPO_ROOT}"
  exit 1
fi

git_numstat="$(git -C "${REPO_ROOT}" log --since="${DAYS} days ago" --reverse --pretty=format:'@@@ %ct' --numstat --)"

calc_result="$(
  awk -v rework_window_seconds="$((DAYS * 24 * 60 * 60))" '
    BEGIN {
      current_ts = 0
      total = 0
      rework = 0
    }
    /^@@@ / {
      current_ts = $2 + 0
      next
    }
    NF == 3 && $1 ~ /^[0-9]+$/ && $2 ~ /^[0-9]+$/ {
      churn = $1 + $2
      file = $3
      total += churn
      if (!(file in first_seen_ts)) {
        first_seen_ts[file] = current_ts
      } else if ((current_ts - first_seen_ts[file]) <= rework_window_seconds) {
        rework += churn
      }
    }
    END {
      printf "%d %d\n", total, rework
    }
  ' <<<"${git_numstat}"
)"

TOTAL_LINES="${calc_result%% *}"
REWORK_LINES="${calc_result##* }"

if [ "${TOTAL_LINES}" -gt 0 ]; then
  REWORK_RATE="$(awk -v r="${REWORK_LINES}" -v t="${TOTAL_LINES}" 'BEGIN { printf "%.1f", (r * 100.0) / t }')"
else
  REWORK_RATE="0.0"
fi

if awk -v v="${REWORK_RATE}" 'BEGIN { exit !(v > 20.0) }'; then
  REWORK_NOTE="❌ Stop feature delivery; instruction quality likely drifting."
elif awk -v v="${REWORK_RATE}" 'BEGIN { exit !(v > 10.0) }'; then
  REWORK_NOTE="⚠️ Watch closely; review prompts and acceptance criteria quality."
else
  REWORK_NOTE="✅ Healthy; rework is inside target."
fi

MERGE_COMMITS="$(git -C "${REPO_ROOT}" log --since="${DAYS} days ago" --merges --pretty=format:'%H')"
PRS_MERGED=0
PRS_WITH_REVISION=0

if [ -n "${MERGE_COMMITS}" ]; then
  while IFS= read -r merge_sha; do
    [ -z "${merge_sha}" ] && continue
    PRS_MERGED=$((PRS_MERGED + 1))
    branch_commit_count="$(git -C "${REPO_ROOT}" rev-list --count "${merge_sha}^1..${merge_sha}^2" 2>/dev/null || echo "0")"
    if [ "${branch_commit_count}" -gt 1 ]; then
      PRS_WITH_REVISION=$((PRS_WITH_REVISION + 1))
    fi
  done <<< "${MERGE_COMMITS}"
fi

if [ "${PRS_MERGED}" -gt 0 ]; then
  PR_REVISION_RATE="$(awk -v r="${PRS_WITH_REVISION}" -v t="${PRS_MERGED}" 'BEGIN { printf "%.1f", (r * 100.0) / t }')"
else
  PR_REVISION_RATE="0.0"
fi

if [ "${PRS_MERGED}" -eq 0 ]; then
  PR_NOTE="No merged PRs found in the window."
elif awk -v v="${PR_REVISION_RATE}" 'BEGIN { exit !(v > 40.0) }'; then
  PR_NOTE="❌ High revision load; tighten issue specs and acceptance criteria."
elif awk -v v="${PR_REVISION_RATE}" 'BEGIN { exit !(v > 25.0) }'; then
  PR_NOTE="⚠️ Above target; inspect recurring review comments."
else
  PR_NOTE="✅ Healthy review flow."
fi

read -r -d '' AUTO_BLOCK <<EOF || true
<!-- METRICS_AUTO:START -->
## Latest Automated Snapshot

Generated by \`npm run metrics\` on **${SNAPSHOT_UTC}** for the last **${DAYS} days**.

| Metric | Value | Notes |
|---|---:|---|
| Rework rate | ${REWORK_RATE}% (${REWORK_LINES}/${TOTAL_LINES} changed lines) | ${REWORK_NOTE} |
| PR revision rate | ${PR_REVISION_RATE}% (${PRS_WITH_REVISION}/${PRS_MERGED} merged PRs revised) | ${PR_NOTE} |
| CI cycle time | _stub_ | Add GitHub Actions duration export, then replace this row with p50/p95 minutes. |

### CI cycle time stub instructions

1. Export workflow durations from GitHub Actions (for example via \`gh run list --json createdAt,updatedAt\`).
2. Compute p50 and p95 run duration for the same ${DAYS}-day window.
3. Replace the CI row above with measured values and trend notes.
<!-- METRICS_AUTO:END -->
EOF

echo ""
echo "═══════════════════════════════════════════"
echo "  [PROJECT NAME] Weekly Metrics"
echo "  Period: last ${DAYS} days"
echo "═══════════════════════════════════════════"
echo " Rework rate: ${REWORK_RATE}% (${REWORK_LINES}/${TOTAL_LINES})"
echo " PR revision rate: ${PR_REVISION_RATE}% (${PRS_WITH_REVISION}/${PRS_MERGED})"
echo " CI cycle time: stub (see docs/METRICS.md instructions)"

if [ "${DRY_RUN}" -eq 1 ]; then
  echo ""
  echo "(dry-run mode) Generated markdown preview:"
  echo ""
  printf "%s\n" "${AUTO_BLOCK}"
  echo ""
  exit 0
fi

if [ ! -f "${METRICS_DOC}" ]; then
  echo "Missing metrics doc: ${METRICS_DOC}"
  echo "Create or restore docs/METRICS.md before running npm run metrics."
  exit 1
fi

tmp_file="$(mktemp)"
AUTO_BLOCK="${AUTO_BLOCK}" python3 - "${METRICS_DOC}" <<'PY' >"${tmp_file}"
import os
import pathlib
import re
import sys

metrics_path = pathlib.Path(sys.argv[1])
content = metrics_path.read_text(encoding="utf-8")
block = os.environ["AUTO_BLOCK"]
pattern = r"<!-- METRICS_AUTO:START -->.*?<!-- METRICS_AUTO:END -->"

if re.search(pattern, content, flags=re.S):
    updated = re.sub(pattern, block, content, flags=re.S)
else:
    updated = content.rstrip() + "\n\n" + block + "\n"

print(updated, end="")
PY

mv "${tmp_file}" "${METRICS_DOC}"

echo ""
echo "Updated ${METRICS_DOC} with latest markdown summary."
echo "═══════════════════════════════════════════"
echo ""
